### ISSUE TITLE
Improve control selection/creation UI in Acquisition Panel

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-instrumentation-kit#156]
```[tasklist]
### Tasks
- [ ] Units should not be harcoded to "m" because controls can have various units
- [ ] The current way controls with scaling are defined can be confusing to users. We should come up with a better way for that.
- [ ] Allow users to specify arbitrary frame parameters for being changed instead of just some hardcoded options (like fov). For example the scan rotation is an important one and being able to set this directly and not via an AS2 control would make the setup a lot easier.
```
