### ISSUE TITLE
Update acquisition documentation with description of acquisition panel

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift-instrumentation-kit#183]
The starting point for this project:

https://github.com/nion-software/nionswift-instrumentation-kit/tree/master/docs

The final web page is rendered here:

https://nionswift-instrumentation.readthedocs.io/en/latest/

```[tasklist]
### Tasks
- [ ] Describe high level concepts like devices, channels, views, procedures
- [ ] Describe typical data formats (1d, 2d, SI, 4D, others)
- [ ] Describe acquisition procedures
```
